stages:
  - build
  - deploy
  - stop

include:
  - local: "terraform/.gitlab-ci.yml"

docker:
  stage: build
  needs: []
  tags:
    - nix
  interruptible: true
  script:
    - nix-env -iA nixpkgs.skopeo
    - nix --extra-experimental-features "nix-command flakes" build -L .#docker-image
    - skopeo login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - skopeo copy --insecure-policy docker-archive:result docker://${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG} --digestfile image-hash
  artifacts:
    paths:
      - image-hash
