name: On Push to main

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.digest.outputs.digest }}
    steps:
      - uses: cachix/install-nix-action@v27
      - run: nix profile install nixpkgs#skopeo
      - run: skopeo login -u "${{ github.repository_owner }}" -p "${{ github.token }}" ghcr.io

      - uses: actions/checkout@v4
      - run: nix build -L .#docker-image
      - run: skopeo copy --insecure-policy docker-archive:result docker://ghcr.io/${{ github.repository }}:main --digestfile image-hash
      - id: digest
        run: echo "digest=$(cat image-hash)" >> $GITHUB_OUTPUT
